#!/bin/sh
#
# Called in response to changes in the cvs repository of memchan
# Assumes that the changed files were already retrieved. Uses them to
# regenerate the whole website.

# pwd = /home/groups/m/me/memchan/

# Remove old temporary information.

rm -rf doc 
mkdir  doc

cp -r memchan/doc/*    doc/
cp -r memchan/htdocs/* htdocs/

# Regenerate the external representatons of all manpages, and the site
# itself. At last generate bundles of the documentation for download.

out=$HOME/logs/crontab
mkdir -p `dirname $out`
rm $out ; touch $out

cd doc    ; ../tools/manpage_regen  >>$out ; cd ..
cd htdocs ; ../tools/htdocs_refresh        ; cd ..

tar cfz memchan.nroff.tar.gz   doc/*.n
tar cfI memchan.nroff.tar.bz2  doc/*.n
zip     memchan.nroff.tar.zip  doc/*.n		> /dev/null
tar cfz memchan.html.tar.gz    doc/*.html
tar cfI memchan.html.tar.bz2   doc/*.html
zip     memchan.html.tar.zip   doc/*.html	> /dev/null
tar cfz memchan.tmml.tar.gz    doc/*.tmml
tar cfI memchan.tmml.tar.bz2   doc/*.tmml
zip     memchan.tmml.tar.zip   doc/*.tmml	> /dev/null

mkdir -p     htdocs/doc
mv memchan.* htdocs/doc/

(sleep 5 ; cp -r memchan/tools/*  tools/) &

exit
